language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install coverage
  - pip install tkouter
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
