language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install coveralls
  - pip install jinja2
  - pip install lxml
  - pip install tinycss
  - pip install cssselect
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - coverage run -m unittest discover
after_success:
  - coveralls
